import type { Theme } from './createTheme'

const decl = (tokens: Record<string, string>, indent = '  ') =>
  Object.entries(tokens)
    .map(([k, v]) => `${indent}--se-${k}: ${v};`)
    .join('\n')

/**
 * 테마 → CSS.
 * 세 가지 상태를 모두 다룬다: 아무 표시 없음(system) / data-theme=light / data-theme=dark.
 */
export function themeToCss(theme: Theme): string {
  const d = theme.identity.density
  return [
    `/* generated by @se/tokens — ${theme.identity.name} (hue ${theme.identity.accent.hue}) */`,
    `:root {`,
    `  color-scheme: light;`,
    decl(theme.static),
    decl(theme.light),
    decl(theme.density[d]),
    `}`,
    `@media (prefers-color-scheme: dark) {`,
    `  :root:not([data-theme="light"]) {`,
    `    color-scheme: dark;`,
    decl(theme.dark, '    '),
    `  }`,
    `}`,
    `:root[data-theme="dark"] {`,
    `  color-scheme: dark;`,
    decl(theme.dark),
    `}`,
    `[data-density="compact"] {`,
    decl(theme.density.compact),
    `}`,
    `[data-density="comfortable"] {`,
    decl(theme.density.comfortable),
    `}`,
    ``,
  ].join('\n')
}
